config/urls.py
from config import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("", include("users.urls", namespace="users")),
]

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import (BlockMailingView, HomeView, MailingAttemptListView, MailingCreateView, MailingDeleteView,
                           MailingDetailView, MailingListView, MailingUpdateView, MessageCreateView, MessageDeleteView,
                           MessageDetailView, MessageListView, MessageUpdateView, RecipientCreateView,
                           RecipientDeleteView, RecipientDetailView, RecipientListView, RecipientUpdateView,
                           SendMailingView)

app_name = MailingConfig.name

urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("recipient_create/", RecipientCreateView.as_view(), name="recipient_create"),
    path(
        "recipient/<int:pk>/delete/",
        RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    path("recipient_list/", cache_page(30)(RecipientListView.as_view()), name="recipient_list"),
    path(
        "recipient_detail/<int:pk>/",
        RecipientDetailView.as_view(),
        name="recipient_detail",
    ),
    path(
        "recipient_update/<int:pk>/",
        RecipientUpdateView.as_view(),
        name="recipient_update",
    ),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("message_list/", cache_page(30)(MessageListView.as_view()), name="message_list"),
    path("message_detail/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("message_update/<int:pk>/", MessageUpdateView.as_view(), name="message_update"),
    path("mailing_create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing_list/", MailingListView.as_view(), name="mailing_list"),
    path("mailing_detail/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing_update/<int:pk>/", MailingUpdateView.as_view(), name="mailing_update"),
    path("<int:pk>", SendMailingView.as_view(), name="send_mailing"),
    path(
        "attempt_list/",
        MailingAttemptListView.as_view(),
        name="attempt_list",
    ),
    path(
        "mailing_block/<int:mailing_id>/block/",
        BlockMailingView.as_view(),
        name="mailing_block",
    ),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig

from .views import BlockUserView, RegisterView, UserDetailList, UserListView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailing:home"), name="logout"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("user_detail/<int:pk>", UserDetailList.as_view(), name="user_detail"),
    path("user_block/<int:user_id>", BlockUserView.as_view(), name="user_block"),
]

mailing/models.py
from django.db import models

from users.models import CustomUser


class Recipient(models.Model):
    email = models.EmailField(unique=True, verbose_name="Email")
    full_name = models.CharField(max_length=100, verbose_name="Ф.И.О")
    comment = models.TextField(null=True, blank=True, verbose_name="Комментарий")
    owner = models.ForeignKey(CustomUser, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="Владелец")

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "Получатель"
        verbose_name_plural = "Получатели"
        ordering = ["full_name"]
        permissions = [("can_view_mailings_of_all_recipients", "can view mailings of all recipients")]


class Message(models.Model):
    subject = models.CharField(max_length=150, verbose_name="Тема письма")
    body_of_the_letter = models.TextField(verbose_name="Тело письма")
    owner = models.ForeignKey(CustomUser, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="Владелец")

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["subject"]
        permissions = [("can_view_all_message", "can view all message")]


class Mailing(models.Model):
    STATUS_CHOICES = [
        ("Создана", "Создана"),
        ("Запущена", "Запущена"),
        ("Завершена", "Завершена"),
        ("Блокирована", "Блокирована"),
    ]
    start_time = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время первой отправки")
    end_time = models.DateTimeField(auto_now=True, verbose_name="Дата и время окончания отправки")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Создана", verbose_name="Статус")
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    recipients = models.ManyToManyField(Recipient, verbose_name="Получатели")
    owner = models.ForeignKey(CustomUser, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="Владелец")
    is_block = models.BooleanField(default=False, verbose_name="Блокировка")

    def __str__(self):
        return f"Рассылка сообщения: {self.message}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ["start_time", "status"]
        permissions = [
            ("can_view_mailings_of_all_recipients", "can view mailings of all recipients"),
            ("can_block_mailings", "can block mailings"),
        ]


class MailingAttempt(models.Model):
    STATUS_CHOICES = [("Успешно", "Успешно"), ("Не успешно", "Не успешно")]
    date_time_of_attempt = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Не успешно", verbose_name="Статус")
    mail_server_response = models.TextField(verbose_name="Ответ почтового сервера")
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    owner = models.ForeignKey(CustomUser, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="Владелец")

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылок"
        ordering = ["date_time_of_attempt"]

mailing/forms.py
from django import forms

from mailing.models import Mailing, Message, Recipient


class RecipientForm(forms.ModelForm):
    """Класс формы клиента"""

    class Meta:
        model = Recipient
        fields = ["full_name", "email", "comment"]


class MessageForm(forms.ModelForm):
    """Класс формы сообщения"""

    class Meta:
        model = Message
        fields = ["subject", "body_of_the_letter", "owner"]
        widgets = {
            "body_of_the_letter": forms.Textarea(attrs={"placeholder": "Введите сообщение..."}),
        }


class MailingForm(forms.ModelForm):
    """Класс формы для рассылки"""

    class Meta:
        model = Mailing
        fields = ["message", "recipients", "status"]

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if user.is_authenticated:
            self.fields["recipients"].queryset = Recipient.objects.filter(owner=user)
            self.fields["message"].queryset = Message.objects.filter(owner=user)
        else:
            self.fields["recipients"].queryset = Recipient.objects.none()
            self.fields["message"].queryset = Message.objects.none()

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from mailing.forms import MailingForm, MessageForm, RecipientForm
from mailing.mixins import OwnerRequiredMixin
from mailing.services import get_mailing_from_cache, get_message_from_cache, get_recipient_from_cache, send_mailing

from .models import Mailing, MailingAttempt, Message, Recipient


class HomeView(ListView):
    model = Mailing
    template_name = "mailing/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["all_mailings"] = Mailing.objects.count()
        context["active_mailings"] = Mailing.objects.filter(
            status="Запущена",
        ).count()
        context["unique_recipients"] = Recipient.objects.values_list("email", flat=True).distinct().count()

        return context


class RecipientListView(ListView):
    model = Recipient
    template_name = "mailing/recipient_list.html"
    context_object_name = "recipients"

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.has_perm("can_view_mailings_of_all_recipients"):
            return Recipient.objects.all()
        else:
            user = self.request.user
            return Recipient.objects.filter(owner=user)


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    template_name = "mailing/recipient_create.html"
    success_url = reverse_lazy("mailing:home")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class RecipientUpdateView(OwnerRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm
    template_name = "mailing/recipient_create.html"
    success_url = reverse_lazy("mailing:recipient_list")


class RecipientDeleteView(OwnerRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Recipient
    template_name = "mailing/recipient_delete.html"
    success_url = reverse_lazy("mailing:recipient_list")

    def test_func(self):
        return (
            self.request.user.is_authenticated
            and self.request.user.has_perm("mailing.recipient_delete")
            or self.request.user.owner
        )

    def handle_no_permission(self):
        return redirect("mailing:recipient_list")


class RecipientDetailView(DetailView):
    model = Recipient
    template_name = "mailing/recipient_detail.html"
    context_object_name = "recipient"


class MessageListView(ListView):
    model = Message
    template_name = "mailing/message_list.html"
    context_object_name = "messages"

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.has_perm("can_view_all_message"):
            return get_message_from_cache()
        else:
            user = self.request.user
            return Message.objects.filter(owner=user)


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    template_name = "mailing/message_create.html"
    success_url = reverse_lazy("mailing:home")

    def form_valid(self, form):
        message = form.save(commit=False)
        message.owner = self.request.user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(OwnerRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = "mailing/message_create.html"
    success_url = reverse_lazy("mailing:message_list")


class MessageDeleteView(OwnerRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Message
    template_name = "mailing/message_delete.html"
    success_url = reverse_lazy("mailing:message_list")

    def test_func(self):
        return (
            self.request.user.is_authenticated
            and self.request.message.owner
            and self.request.user.has_perm("mailing.message_delete")
        )

    def handle_no_permission(self):
        return redirect("mailing:message_list")


class MessageDetailView(DetailView):
    model = Message
    template_name = "mailing/message_detail.html"
    context_object_name = "message"


class MailingListView(ListView):
    model = Mailing
    template_name = "mailing/mailing_list.html"
    context_object_name = "mailings"

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.has_perm("can_view_mailings_of_all_recipients"):
            return get_mailing_from_cache()

        else:
            return Mailing.objects.filter(owner=self.request.user)


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_create.html"
    success_url = reverse_lazy("mailing:home")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class MailingUpdateView(OwnerRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_create.html"
    success_url = reverse_lazy("mailing:mailing_list")


class MailingDeleteView(OwnerRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Mailing
    template_name = "mailing/mailing_delete.html"
    success_url = reverse_lazy("mailing:mailing_list")

    def test_func(self):
        return (
            self.request.user.is_authenticated
            and self.request.user.has_perm("mailing.mailing_delete")
            or self.request.mailing.owner
        )

    def handle_no_permission(self):
        return redirect("mailing:mailing_list")

    def get_object(self, queryset=None):
        return get_object_or_404(Mailing, pk=self.kwargs["pk"])


class MailingDetailView(DetailView):
    model = Mailing
    template_name = "mailing/mailing_detail.html"
    context_object_name = "mailing"


class SendMailingView(View):
    def get(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)
        response = send_mailing(mailing)
        return render(request, "mailing_detail.html", {"mailing": mailing, "response": response})


class MailingAttemptListView(ListView):
    model = MailingAttempt
    template_name = "mailing/attempt_list.html"
    context_object_name = "attempt_list"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(mailing__owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context["attempts_count"] = queryset.count()
        context["attempts_success_count"] = queryset.filter(status="Успешно").count()
        context["attempts_error_count"] = queryset.filter(status="Не успешно").count()
        return context


class BlockMailingView(LoginRequiredMixin, View):

    def get(self, request, mailing_id):
        mailing = get_object_or_404(Mailing, id=mailing_id)
        return render(request, "mailing/mailing_block.html", {"mailing": mailing})

    def post(self, request, mailing_id):
        mailing = get_object_or_404(Mailing, id=mailing_id)

        if not request.user.has_perm("mailing.can_block_mailings"):
            return HttpResponseForbidden("У вас нет прав для блокировки рассылки.")

        mailing.is_block = not mailing.is_block

        mailing.status = "Блокирована" if mailing.status != "Блокирована" else "Создана"
        mailing.save()

        return redirect("mailing:attempt_list")

mailing/templates/mailing/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cервис по управлению рассылками</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">

</head>
<body>
{% include 'includes/inc_menu.html'%}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Cервис по управлению рассылками</h1>
</div>
{% block content %}
{% endblock %}
{% include 'includes/footer.html'%}

<script type="text/javascript" src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/mailing/home.html
{% extends 'mailing/base.html'%}

{% block title %}Главная{% endblock %}

{% block content %}

<p>Общее количество рассылок: </p>
<p>Количество активных рассылок: </p>
<p>Количество уникальных получателей: </p>

{% endblock %}

mailing/templates/mailing/mailing_block.html
{% extends 'mailing/base.html' %}
{% block title %} Блокировка рассылки {% endblock %}
{% block content %}
<div class="container mt-5">

    <h1 class="mb-4">
        {% if mailing.is_block %}
            Разблокировать рассылку
        {% else %}
            Заблокировать рассылку
        {% endif %}
    </h1>
    <p>Вы уверены, что хотите {% if mailing.is_block %}разблокировать{% else %}
        заблокировать{% endif %} рассылку "{{ mailing.id }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">
            {% if mailing.is_block %}
                Разблокировать
            {% else %}
                Заблокировать
            {% endif %}
        </button>
        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/mailing_create.html
{% extends 'mailing/base.html' %}
{% block title %}Добавить рассылку{% endblock %}
{% block content %}
<div class="card mt-4">
    <div class="card-header">
        <h2 class="mb-1">Добавить рассылку</h2>
    </div>
        <form method="post" enctype="multipart/form-data>">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
</div>
{% endblock %}

mailing/templates/mailing/mailing_delete.html
{% extends 'mailing/base.html' %}
{% block title %}Удалить рассылку{% endblock %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Удалить рассылку</h1>
    <p>Вы уверены, что хотите удалить рассылку с текстом: "{{ object.message }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'mailing:mailing_detail' mailing.id %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends "mailing/base.html" %}

{% block title %}Информация о рассылке{% endblock %}

{% block content %}

<div class="card mt-4">
    <div class="card-header">
        <h2 class="card-title">Информация о рассылке {{ mailing.pk }}</h2>
    </div>
    {% if user == mailing.owner or user.is_staff or perms.mailing.can_view_mailings_of_all_recipients  %}
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Дата и время первой отправки:
                    {{ mailing.start_time|date:"d.M.Y H:i:s" }}</li>
                <li class="list-group-item">Дата и время окончания отправки:
                    {{ mailing.end_time|date:"d.M.Y H:i:s" }}</li>
                <li class="list-group-item">Тема сообщения: {{ mailing.message.subject }}</li>
                <li class="list-group-item">Текст сообщения: {{ mailing.message.body_of_the_letter }}</li>
                <li class="list-group-item">Статус: {{ mailing.get_status_display }}</li>
                <li class="list-group-item">Получатели:
                    <ul>
                        {% for recipient in mailing.recipient.all %}
                        <li>{{ recipient.full_name }} ({{ recipient.email }})</li>
                        {% empty %}
                            <li>Нет получателей</li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>
        <div class="card-footer">
            <div class="btn-group">
                {% if perms.spam.can_disable_mailings or user.is_staff or perms.mailing.can_block_mailings %}
                    {% if mailing.is_block %}
                        <td><a href="{% url 'mailing:mailing_block' mailing.id %}" class="btn btn-warning">Разблокировать рассылку</a></td>
                    {% else %}
                        <td><a href="{% url 'mailing:mailing_block' mailing.id %}" class="btn btn-warning">Заблокировать рассылку</a></td>
                    {% endif %}
                {% endif %}
                {% if user == mailing.owner or user.is_staff %}
                    {% if not mailing.is_block %}
                        <a href="{% url 'mailing:start_mailing' mailing.pk %}" class="btn btn-success">
                            {% if mailing.status == "Создана" %}
                                Отправить рассылку
                            {% else %}
                                Отправить повторно
                            {% endif %}
                        </a>
                    {% endif %}
                    <a href="{% url 'mailing:mailing_update' mailing.pk %}" class="btn btn-primary">
                        Редактировать
                    </a>
                    <a href="{% url 'mailing:mailing_delete' mailing.pk %}" class="btn btn-danger">
                        Удалить
                    </a>
                {% endif %}
                <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary">
                    Назад
                </a>
            </div>
        </div>
    {% endif %}
</div>

{% endblock %}

mailing/templates/mailing/message_create.html
{% extends 'mailing/base.html' %}
{% block title %}Добавить сообщение{% endblock %}
{% block content %}
<div class="card mt-4">
    <div class="card-header">
        <h2 class="mb-1">Добавить сообщение</h2>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.subject.label_tag }}
            {{ form.subject }}
        </div>
        <div class="form-group" style="margin-top: 15px;">
            {{ form.body_of_the_letter }}
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'mailing:message_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/message_delete.html
{% extends 'mailing/base.html' %}
{% block title %}Удалить сообщение{% endblock %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Удалить сообщение</h1>
    <p>Вы уверены, что хотите удалить сообщение с темой письма "{{ object.subject }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'mailing:message_detail' message.id %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends "mailing/base.html" %}

{% block title %}Информация о сообщении{% endblock %}

{% block content %}


<div class="card mt-4">
    <div class="card-header">
        <h2 class="card-title">Информация о сообщении</h2>
    </div>
    {% if message.owner == user or perms.mailing.can_view_all_messages %}
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Тема: {{ message.subject }}</li>
            <li class="list-group-item">Текст сообщения: {{ message.body_of_the_letter }}</li>
        </ul>
    </div>
    <div class="card-footer">
        <div class="btn-group">
            <a href="{% url 'mailing:message_update'  message.pk %}" class="btn btn-primary">
                Редактировать
            </a>
            <a href="{% url 'mailing:message_delete' message.pk %}" class="btn btn-danger">
                Удалить
            </a>
    {% endif %}
            <a href="{% url 'mailing:message_list' %}" class="btn btn-secondary">
                Назад
            </a>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block title %}Список сообщений{% endblock %}

{% block content %}

<div class="card mt-4">
    <div class="card-header">
        <h2 class="mb-1">Список сообщений</h2>
    </div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'mailing:message_create' %}">
            Добавить сообщение
        </a>
        {% endif %}
    </div>
    <div class="table-responsive small">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">Тема сообщения</th>
                </tr>
            </thead>
            <tbody>
                {% if messages %}
                    {% for message in messages %}
                        {% if user == message.owner or user.is_staff or perms.mailing.can_view_all_message or user.is_authenticated %}
                            <tr>
                                <td>
                                    <a href="{% url 'mailing:message_detail' message.id %}">{{ message.subject }}</a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="1">Нет сообщений.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/recipient_create.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="card mt-4">
    <div class="card-header">
        <h2 class="mb-1">Добавить получателя</h2>
    </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'mailing:recipient_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
</div>
{% endblock %}

mailing/templates/mailing/recipient_delete.html
{% extends 'mailing/base.html' %}
{% block title %}Удалить получателя{% endblock %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Удалить получателя</h1>
    <p>Вы уверены, что хотите удалить получателя "{{ object.full_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'mailing:recipient_detail' recipient.id %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/recipient_detail.html
{% extends 'mailing/base.html' %}
{% block title %}Информация о получателе{% endblock %}
{% include 'includes/inc_menu.html' %}
{% block content %}

<div class="card mt-4">
    <div class="card-header">
        <h2 class="card-title">Информация о получателе</h2>
    </div>
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">ФИО: {{ recipient.full_name }}</li>
            <li class="list-group-item">Email: {{ recipient.email }}</li>
            <li class="list-group-item">Комментарий: {{ recipient.comment|truncatechars:30 }}</li>
        </ul>
    </div>
    <div class="card-footer">
        <div class="btn-group">
            {% if recipient.owner == user or perms.user.recipient_delete %}
            <a href="{% url 'mailing:recipient_update' recipient.id %}" class="btn btn-primary">
                Редактировать
            </a>
            <form action="{% url 'mailing:recipient_delete' recipient.id %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Удалить</button>
            </form>
            {% endif %}
            <a href="{% url 'mailing:recipient_list' %}" class="btn btn-secondary">
                Назад
            </a>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/recipient_list.html
{% extends 'mailing/base.html'%}

{% block title %}Список получателей{% endblock %}

{% block content %}

<div class="card mt-4">
    <div class="card-header">
        <h2 class="mb-1">Список получателей</h2>
    </div>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'mailing:recipient_create' %}">
        Добавить получателя
    </a>
    {% endif %}
</div>
<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th scope="col">Ф.И.О</th>
                <th scope="col">Email</th>
                <th scope="col">Комментарий</th>
            </tr>
        </thead>
        <tbody>
            {% if recipients %}
                {% for recipient in recipients %}
                    {% if user == recipient.owner or user.is_staff or perms.mailing.can_view_mailings_of_all_recipients or user.is_authenticated%}
                        <tr>
                            <td>
                                <a href="{% url 'mailing:recipient_detail' recipient.id %}">{{ recipient.full_name }}</a>
                            </td>
                            <td>{{ recipient.email }}</td>
                            <td>{{ recipient.comment|truncatechars:30 }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% else %}
                 <tr>
                    <td colspan="3">Нет получателей.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>
</div>
{% endblock %}