config/urls.py
from config import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("", include("users.urls", namespace="users")),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig

from .views import BlockUserView, RegisterView, UserDetailList, UserListView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailing:home"), name="logout"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("user_detail/<int:pk>", UserDetailList.as_view(), name="user_detail"),
    path("user_block/<int:user_id>", BlockUserView.as_view(), name="user_block"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    username = models.CharField(max_length=50, unique=True, blank=False)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    avatar = models.ImageField(upload_to="users/avatars/", blank=True, null=True, verbose_name="Аватар")
    country = models.CharField(max_length=50, blank=True, null=True, verbose_name="Страна", help_text="Укажите страну")
    token = models.CharField(max_length=100, blank=True, null=True, verbose_name="Токен")
    is_block = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = [
        "username",
    ]

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_block_user", "can block user"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        help_text="Необязательное поле. Введите номер телефона, состоящий только из цифр.",
    )
    username = forms.CharField(max_length=50, required=False)

    class Meta:
        model = CustomUser
        fields = ("email", "first_name", "last_name", "avatar", "username", "phone_number", "password1", "password2")

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")

        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен состоять только из цифр.")
        return phone_number

    def clean_avatar(self):
        cleaned_data = super().clean()
        avatar = cleaned_data.get("avatar")

        if avatar is None:
            return None

        max_size = 5 * 1024 * 1024
        if avatar.size > max_size:
            raise forms.ValidationError("Размер файла превышает 5 MB.")
        if not avatar.name.lower().endswith((".jpg", ".jpeg", ".png")):
            raise forms.ValidationError(
                "Формат файла не поддерживается. Допустимый формат файла: *.jpg, *.jpeg, *.png"
            )
        return avatar

    def clean_username(self):
        username = self.cleaned_data.get("username")

        if username and CustomUser.objects.filter(username=username).exists():
            raise forms.ValidationError(f"Пользователь с именем {username} уже существует")
        return username

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView, ListView

from config.settings import EMAIL_HOST_USER
from users.forms import CustomUserCreationForm

from .models import CustomUser


class RegisterView(CreateView):
    model = CustomUser
    template_name = "users/register.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("users: login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"

        send_mail(
            subject="Подтверждение почты",
            message=f"Для подтверждения почты перейдите по ссылке {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(CustomUser, token=token)
    user.is_active = True
    user.save()
    return redirect("users:login")


class UserListView(ListView):
    model = CustomUser
    template_name = "users/user_list.html"
    context_object_name = "users_list"

    def get_queryset(self):
        return CustomUser.objects.all()


class UserDetailList(DetailView):
    model = CustomUser
    template_name = "users/user_detail.html"
    context_object_name = "user_detail"


class BlockUserView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(CustomUser, id=user_id)
        if not request.user.has_perm("users.can_block_user"):
            return HttpResponseForbidden("Недостаточно прав для блокировки.")
        return render(request, "user_block.html", {"user": user})

    def post(self, request, user_id):
        user = get_object_or_404(CustomUser, id=user_id)

        if not request.user.has_perm("users.can_block_user"):
            return HttpResponseForbidden("Недостаточно прав для блокировки.")

        user.is_block = not user.is_block
        user.save()

        return redirect("users:user_list")

users/templates/users/login.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Вход на сайт</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Регистрация</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </form>
</div>
{% endblock %}

users/templates/users/user_block.html
{% extends 'mailing/base.html' %}
{% block title %} Блокировка пользователя {% endblock %}
{% block content %}
<div class="container mt-5">

    <h1 class="mb-4">
        {% if user.is_block%}
            Разблокировать пользователя
        {% else %}
            Заблокировать пользователя
        {% endif %}
    </h1>
    <p>Вы уверены, что хотите {% if user.is_block %}разблокировать{% else %}заблокировать{% endif %} пользователя "{{ user.email }}"?</p>

    <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">
        {% if user.is_blocked %}
            Разблокировать
        {% else %}
            Заблокировать
        {% endif %}
    </button>
    <a href="{% url 'users:user_list' %}" class="btn btn-secondary">Отмена</a>
</form>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailing/base.html' %}
{% block title %}Детали пользователя{% endblock %}
{% load my_tags %}
{% block content %}
<h1>Детали пользователя: {{ user.username }}</h1>

<div class="user-details">
    <img src="{{ user.avatar | media_filter }}" class="card-img-top" alt="avatar"
         style="max-width: 150px; max-height: 150px; width: auto; height: auto;">

    <ul>
    <li><strong>Email:</strong> {{ user.email }}</li>
    <li><strong>Имя:</strong> {{ user.first_name }}</li>
    <li><strong>Телефон:</strong> {{ user.phone_number }}</li>
    <li><strong>Страна:</strong> {{ user.country }}</li>
    </ul>
    <div class="card">
        <div class="card-body">
            <a href="{% url 'mailing:home' %}" class="btn btn-secondary">Назад</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_list.html
{% extends "mailing/base.html" %}
{% load my_tags %}
{% block title %}Список пользователей{% endblock %}
{% block content %}
<div class="card mt-4">
    <div class="card-header">
        <h2 class="mb-1">Список пользователей</h2>
    </div>
<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Email</th>
                <th>Ф. И. О.</th>
                <th>Nikcname</th>
                <th>Телефон</th>
                <th>Аватар</th>
                <th>Страна</th>
                <th>Статус</th>

            </tr>
        </thead>
        <tbody>
            {% for user in user_list %}
                {% if perms.users.can_block_user and not user.is_superuser %}
                <tr>
                    <td>{{ user.email }}</td>
                    <td>{{ user.first_name }} {{user.last_name}}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.phone_number }}</td>
                    <td><img src="{{ user.avatar | media_filter }}" class="card-img-top" alt="avatar"
                         style="max-width: 150px; max-height: 150px; width: auto; height: auto;"></td>
                    <td>{{ user.country }}</td>
                    <td>
                        {% if user.is_block %}
                            Заблокировано
                        {% else %}
                            Разблокировано
                        {% endif %}
                    </td>
                    {% if perms.users.can_block_user or user.is_staff %}
                    {% if user.is_block %}
                        <td><a href="{% url 'users:user_block' user.id %}">Разблокировать</a></td>
                    {% else %}
                        <td><a href="{% url 'users:user_block' user.id %}">Заблокировать</a></td>
                    {% endif %}
                    {% endif %}
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% endblock %}